# SITE CONFIGURATION
baseurl: "/blog"
url: "http://suyashlakhotia.com"

# THEME-SPECIFIC CONFIGURATION
theme_settings:
  # Meta
  title: Suyash Lakhotia's Blog
  avatar: SL-Square.png
  gravatar: 2a2de496b8f9f7bac32eac19681a4091 # Email MD5 hash
  description: "A collection of observations, thoughts & ideas" # used by search engines

  # Icons
  rss: false
  email_address: # Full email address, e.g. "sam@example.com"
  behance:
  bitbucket:
  dribbble:
  facebook:
  flickr:
  github: "SuyashLakhotia"
  google_plus:
  instagram:
  linkedin:  "https://www.linkedin.com/in/suyashlakhotia/" # Full URL
  pinterest:
  reddit:
  soundcloud:
  stack_exchange: # Full URL
  steam:
  tumblr:
  twitter: "SuyashLakhotia"
  wordpress:
  youtube:

  # Scripts
  google_analytics: # Tracking ID, e.g. "UA-000000-01"
  disqus_shortname:
  muut_community_name: # From muut.com settings, e.g. "muttcommunityname"
  katex: true # Enable if using math markup

  # Colours, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"
  google_fonts: "Source+Sans+Pro:400,700,700italic,400italic"

  # Post navigation
  post_navigation: true

# PAGINATION
paginate: 5
paginate_path: "page/:num"

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: :compressed
plugins: [jekyll-paginate]

# CROSSPOST TO MEDIUM SETTINGS
jekyll-crosspost_to_medium:
  enabled: true
  status: draft
  text: |
    <hr>
    <p><i>This article was originally posted <a href=\"{{ url }}\" rel=\"canonical\">on my own blog</a>.</i></p>
