# SITE CONFIGURATION
url: "http://suyashlakhotia.com"
baseurl: "/blog"

# SITE DETAILS
title: "Suyash Lakhotia's Blog"
description: "A collection of observations, thoughts & ideas"
logo: "img/SL-Square.png"
author: "Suyash Lakhotia"
twitter:
  username: "SuyashLakhotia"
social:
  name: "Suyash Lakhotia"
  links:
    github: "https://github.com/SuyashLakhotia"
    linkedin: "https://www.linkedin.com/in/suyashlakhotia/"
    twitter: "https://twitter.com/SuyashLakhotia"
    facebook: "https://www.facebook.com/suyash.lakhotia"

# THEME-SPECIFIC CONFIGURATION
theme_settings:
  # Meta
  title: "Suyash Lakhotia's Blog"
  avatar: "SL-Square.png"
  gravatar: "2a2de496b8f9f7bac32eac19681a4091" # Email MD5 hash
  description: "A collection of observations, thoughts & ideas" # used by search engines

  # Icons
  rss: true
  email_address: # Full email address, e.g. "sam@example.com"
  behance:
  bitbucket:
  dribbble:
  facebook:
  flickr:
  github: "SuyashLakhotia"
  google_plus:
  instagram:
  linkedin: "https://www.linkedin.com/in/suyashlakhotia/" # Full URL
  pinterest:
  reddit:
  soundcloud:
  stack_exchange: # Full URL
  steam:
  tumblr:
  twitter: "SuyashLakhotia"
  wordpress:
  youtube:

  # Scripts
  google_analytics: # Tracking ID, e.g. "UA-000000-01"
  disqus_shortname:
  muut_community_name: # From muut.com settings, e.g. "muttcommunityname"
  katex: true # Enable if using math markup

  # Colours, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"
  google_fonts: "PT+Serif:400,400i,700,700i|Open+Sans:400,400i,700,700i"

  # Post navigation
  post_navigation: true

# PAGINATION
paginate: 5
paginate_path: "page/:num"

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: :compressed
plugins: [jekyll-paginate, jemoji, jekyll-seo-tag]

# CROSSPOST TO MEDIUM SETTINGS
jekyll-crosspost_to_medium:
  enabled: true
  status: unlisted
  backdate: false
  text: |
    <hr>
    <p><i>This article was originally posted on <a href="http://suyashlakhotia.com/blog/">my blog</a>.</i></p>
